user:
  max_name_size: 50
  max_email_size: 255
  min_pass_size: 6
  index_gravatar_size: 50
  password_reset_time: 2
users_helper:
  gravatar_size: 80
page:
  limit_user: 10
micropost:
  ava_micropost_size: 50
  picture_size: 5
  content_max: 140
picture:
  picture_size: 400
feed:
  feed_number: 10
seed:
  user: 50
  take: 6
  sentence: 5
